"""
WHAT THIS FILE ACTUALLY DOES, IN PLAIN LANGUAGE
------------------------------------------------
This is the last step of the "stack" pipeline: it takes a handful of
retrieved support notes (fuzzy, prose, ranked by similarity) and a compiled
query result (exact numbers, scoped to the specific accounts those notes
named) and stitches them into one answer a human reads.

The risk in handing both to an LLM and saying "write me an answer" is that
an LLM will happily produce a smooth, confident sentence that neither input
actually supports -- it fills gaps and smooths seams by default. So this
module doesn't ask an LLM to be careful about citations; it removes the LLM
from the step entirely and builds every sentence from a template, so a
sentence and its citation are generated by the same line of code, in the
same step. An uncited claim isn't just checked for afterward -- it's not a
thing this code is capable of producing.

WHY THIS MODULE EXISTS
------------------------
A stacking answer merges two things that were computed independently and
know nothing about each other: a handful of retrieved support notes
(tools/retrieve_notes.py -- prose, approximate, ranked by embedding
distance) and a compiled query result (src/compiler/intent_compiler.py via
graph_semantic.py or mcp_server/tools.py -- exact numbers, scoped to
specific user_ids). This module is the one place those two get combined
into a single answer a human reads.

The failure mode this exists to prevent is specific: an LLM asked to
"summarize these notes and numbers into an answer" will, left unconstrained,
smooth over the seams and assert things neither input actually said --
a plausible-sounding sentence with no note_id or number behind it. Layer
5's Definition of Done names this directly: "every claim attributed to
either a note_id or a field in the audit envelope. Unattributed sentences
in the answer are the failure mode to test for." This module's job is to
make that structurally hard to violate, not just to ask nicely for
citations in a prompt.

CONTRACT
--------
    synthesize(question, notes, query_result) -> SynthesisResult

Args, conceptually:
  - notes: list[RetrievedNote] from tools/retrieve_notes.py -- the
    qualitative half. Each has a note_id, user_id, category, and text.
  - query_result: whatever src/graph_semantic.py's state or
    mcp_server/tools.py's QueryResult produced for the structured half --
    rows, the compiled SQL, proven_join_path, semantic_model_version.

Steps:

1. GROUND EVERY FACTUAL CLAIM IN A SOURCE
   Each sentence of the final answer must be traceable to either a specific
   note_id (for a qualitative claim -- "several accounts cited latency
   complaints [note-0031, note-0104]") or a field already present in
   query_result (for a numeric claim -- "combined revenue: $X, per the
   compiled query"). A sentence citing neither is the failure mode.

2. DO NOT LET THE LLM INVENT THE JOIN
   The connection between "these notes" and "these rows" is user_id, and
   that join already happened structurally (the router/caller extracted
   user_ids from the retrieved notes and scoped the compiled query to
   them) -- this module should not ask an LLM to infer or re-derive which
   note belongs to which row. If an LLM call is used at all here, its job
   is narration of already-joined facts, not the joining itself.

3. RETURN THE ATTRIBUTION ALONGSIDE THE PROSE, NOT JUST EMBEDDED IN IT
   SynthesisResult (below) carries `cited_note_ids` and `cited_query_fields`
   as structured lists in addition to the prose `answer`, so a caller (or a
   test) can mechanically verify every citation the prose claims to make
   actually corresponds to a note/field that was actually retrieved/
   computed -- rather than trusting free text to have gotten its own
   footnotes right.

4. AN EMPTY RETRIEVAL RESULT IS A DIFFERENT ANSWER THAN A LOW-CONFIDENCE ONE
   If tools/retrieve_notes.py returns nothing relevant, say so plainly
   ("no matching support notes found") rather than answering from the
   structured half alone and letting the reader assume the qualitative
   question was addressed.

DECISIONS MADE (see the module docstring's original DECISIONS TO MAKE section)
-------------------------------------------------------------------------------

  A. TEMPLATE-BASED SYNTHESIS, OR AN LLM NARRATION PASS?
     Template-based, with no LLM call in this module at all. The reason
     goes further than "templates are easier to audit": building the
     answer from templates makes an uncited sentence IMPOSSIBLE to
     construct, not just easy to catch afterward. Every sentence below is
     generated in the same statement that appends its citation to
     `cited_note_ids`/`cited_query_fields` -- there is no code path that
     produces prose without also producing its citation, so step 3's
     "mechanically verify every citation is real" check is satisfied by
     construction rather than by a separate re-validation pass. The
     tradeoff accepted: the prose reads stiffly rather than naturally. For
     a module whose stated Definition of Done is specifically "test for
     unattributed sentences," removing the LLM from this one step removes
     the failure mode instead of merely detecting it -- worth the stiffer
     prose.

  B. MULTIPLE NOTES NAMING THE SAME user_id?
     Cite all of them, never collapse to "most recent" or pick one --
     dropping a retrieved note from the citation list because another one
     about the same account seemed sufficient would undercut the point of
     an audit trail. Double-counting on the NUMBERS side isn't a concern
     this module has to solve, because of the decision underneath both A
     and B: this module never recomputes or re-aggregates anything. Every
     numeric claim is read verbatim from a field query_result already
     computed once -- however many notes point at the same account, the
     number reported is whatever the compiled query already computed
     correctly, not something this module sums again.

WHAT THIS MODULE MUST NOT DO
------------------------------
- No sentence in `answer` without a corresponding entry in
  `cited_note_ids` or `cited_query_fields` -- see step 3's whole reason for
  existing as a structured, checkable list rather than trusting the prose.
- No re-deriving the note-to-row join here -- that already happened before
  this module was called (see step 2).
- No silently answering only the structured half when retrieval came back
  empty (see step 4) -- that is a partial answer presented as a complete one.

Owner: Ajinkya.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class SynthesisResult:
    """The merged, attributed answer.

    `cited_note_ids` and `cited_query_fields` exist so a caller (or a test)
    can mechanically check that every claim in `answer` traces to something
    real, rather than trusting the prose to have cited itself correctly --
    see the module docstring's step 3.
    """

    answer: str
    cited_note_ids: tuple[str, ...] = ()
    cited_query_fields: tuple[str, ...] = field(default_factory=tuple)
    matched_user_ids: tuple[int, ...] = ()


# ---------------------------------------------------------------------------
# Internal helpers. Not part of the public contract.
# ---------------------------------------------------------------------------


def _get(obj: Any, name: str, default: Any = None) -> Any:
    """Attribute-or-key access that works whether `obj` is a dict (a plain
    state-dict field from graph_semantic.py) or an object with attributes
    (mcp_server/tools.py's QueryResult, a RetrievedNote instance) -- see
    the contract's instruction to read query_result defensively rather than
    assume one exact type. Applied to notes too, for the same reason.
    """
    if obj is None:
        return default
    if isinstance(obj, dict):
        return obj.get(name, default)
    return getattr(obj, name, default)


def _no_notes_result() -> SynthesisResult:
    """Step 4: an empty retrieval result is its own answer, not a silent
    fallback to the structured half. query_result is deliberately not
    consulted here at all -- with no matched user_ids, any numbers it
    contains have no valid join to ground them against, so this module
    does not attempt to use them (see WHAT THIS MODULE MUST NOT DO).
    """
    return SynthesisResult(
        answer=(
            "No matching support notes were found for this question, so no "
            "specific accounts could be identified to scope a structured "
            "lookup against."
        )
    )


# ---------------------------------------------------------------------------
# Public contract
# ---------------------------------------------------------------------------


def synthesize(
    question: str,
    notes: list[Any],
    query_result: Any,
) -> SynthesisResult:
    """Merge retrieved support notes with a compiled query result into one
    attributed answer.

    Args:
        question: the original plain-English question.
        notes: RetrievedNote objects from tools/retrieve_notes.py --
            possibly empty, meaning nothing matched (see step 4).
        query_result: the structured result already computed for the
            user_ids these notes named -- shape depends on which pipeline
            produced it (graph_semantic.py's state dict, or
            mcp_server/tools.py's QueryResult); read defensively rather
            than assuming one exact type.

    Returns:
        SynthesisResult whose `answer` is fully covered by
        `cited_note_ids` / `cited_query_fields` -- see the module docstring's
        "WHAT THIS MODULE MUST NOT DO."

    See the module docstring for the full contract and the two decisions
    (A, B) that have to be made before this can be written.
    """
    if not notes:
        return _no_notes_result()

    # --- collect notes per user_id, and the deduplicated citation/user
    # lists, in first-seen order for determinism -- DECISION B: every note
    # is kept, never collapsed to "most recent" or a single pick. ---
    notes_by_user: dict[Any, list[Any]] = {}
    cited_note_ids: list[str] = []
    matched_user_ids: list[Any] = []

    for note in notes:
        note_id = _get(note, "note_id")
        user_id = _get(note, "user_id")

        if note_id is not None and note_id not in cited_note_ids:
            cited_note_ids.append(note_id)
        if user_id is not None and user_id not in matched_user_ids:
            matched_user_ids.append(user_id)

        notes_by_user.setdefault(user_id, []).append(note)

    sentences: list[str] = []

    # --- qualitative half: one templated sentence per matched account,
    # listing EVERY note that mentioned them (DECISION B). Each sentence is
    # generated in the same step that produced its citation ids above, so
    # there is no sentence here without a note_id behind it. ---
    for user_id in matched_user_ids:
        user_notes = notes_by_user[user_id]
        note_ids_for_user = [
            n_id
            for n_id in (_get(n, "note_id") for n in user_notes)
            if n_id is not None
        ]
        categories = sorted(
            {c for c in (_get(n, "category") for n in user_notes) if c}
        )
        category_phrase = f" ({', '.join(categories)})" if categories else ""
        sentences.append(
            f"Account {user_id} was flagged{category_phrase} in "
            f"[{', '.join(note_ids_for_user)}]."
        )

    # --- quantitative half: read fields query_result ALREADY computed --
    # never recompute or re-aggregate here (see step 2 / DECISION B). ---
    cited_query_fields: list[str] = []
    rows = _get(query_result, "rows") or []
    measure_name = _get(query_result, "measure")
    dimensions = _get(query_result, "dimensions") or ()

    if not rows or not measure_name:
        # A stacking question whose retrieval half matched but whose
        # structured half produced nothing is still a real, honest answer
        # to say out loud -- not silently omitted.
        sentences.append(
            "No structured result was available to report a number "
            "alongside these notes."
        )
    else:
        for i, row in enumerate(rows):
            value = _get(row, measure_name)
            if dimensions:
                dim_bits = ", ".join(
                    f"{dim}={_get(row, dim)}" for dim in dimensions
                )
                sentences.append(
                    f"For {dim_bits}, {measure_name} across these accounts "
                    f"is {value}."
                )
                for dim in dimensions:
                    cited_query_fields.append(f"rows[{i}].{dim}")
            else:
                sentences.append(
                    f"Combined {measure_name} across these "
                    f"{len(matched_user_ids)} accounts is {value}."
                )
            cited_query_fields.append(f"rows[{i}].{measure_name}")

    return SynthesisResult(
        answer=" ".join(sentences),
        cited_note_ids=tuple(cited_note_ids),
        cited_query_fields=tuple(cited_query_fields),
        matched_user_ids=tuple(matched_user_ids),
    )